name: 'Auto Merge PRs'
description: 'A GitHub Action to automatically merge pull requests after they have received the required approvals.'
author: 'MinhOmega'
branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  sleep_duration:
    description: 'Duration to sleep between checks (in seconds)'
    required: false
    default: '5'
  timeout_minutes:
    description: 'Timeout for the merge process (in minutes)'
    required: false
    default: '10'
  base_branch:
    description: 'Base branch to check against'
    required: false
    default: 'master'
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'docker'
  image: 'ghcr.io/minhomega/auto-merge:v1.0.5'
  env:
    SLEEP_DURATION: ${{ inputs.sleep_duration }}
    TIMEOUT_MINUTES: ${{ inputs.timeout_minutes }}
    BASE_BRANCH: ${{ inputs.base_branch }}
    GH_TOKEN: ${{ inputs.github_token }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}
    GITHUB_REPOSITORY: ${{ github.repository }}
